name: OnyroHealing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005d89'
    - '#012f46'
    - '#fefefe'
    - '#5aa048'
    - '#9beaf1'
  brandStrength: 0.5
  lightness: 0.7899649494793266
  saturation: 0.11733066104352474
  rhythmicContrast: 0.5840104958042502
purpose: []
