name: OnyroHealing
favicon: null
layout_spectrum: 0.66319
typography_spectrum: 0.47435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141031'
    - '#104e97'
    - '#2095a7'
    - '#b4d4e9'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
